# Generated by Django 5.2.1 on 2025-12-04 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0005_alter_datasetimage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('lesion_segmentation', '病灶分割'), ('dr_grading', 'DR分级'), ('both', '病灶分割+DR分级')], default='lesion_segmentation', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='处理进度(0-100)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('model_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='模型路径')),
                ('model_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='模型版本')),
                ('result_image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='结果图像路径')),
                ('segmentation_mask_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='分割掩码路径')),
                ('lesion_statistics', models.JSONField(blank=True, default=dict, verbose_name='病灶统计信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('patient_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_tasks', to='datasets.patientimage', verbose_name='患者影像')),
            ],
            options={
                'verbose_name': '诊断任务',
                'verbose_name_plural': '诊断任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=100, unique=True, verbose_name='报告编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待复核'), ('reviewed', '已复核'), ('finalized', '已确认')], default='draft', max_length=20, verbose_name='报告状态')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='AI诊断摘要')),
                ('lesion_summary', models.JSONField(blank=True, default=dict, verbose_name='病灶摘要')),
                ('doctor_notes', models.TextField(blank=True, null=True, verbose_name='医生备注')),
                ('doctor_conclusion', models.TextField(blank=True, null=True, verbose_name='医生结论')),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='PDF报告路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('patient_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='datasets.patientimage', verbose_name='患者影像')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='复核医生')),
                ('diagnosis_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnosis.diagnosistask', verbose_name='诊断任务')),
            ],
            options={
                'verbose_name': '诊断报告',
                'verbose_name_plural': '诊断报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
