# Generated by Django 5.2.1 on 2025-12-04 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='病例标题')),
                ('summary', models.TextField(blank=True, verbose_name='病例摘要')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已结束'), ('archived', '已归档')], default='active', max_length=20, verbose_name='病例状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_records', to=settings.AUTH_USER_MODEL, verbose_name='患者')),
                ('primary_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_record', to='diagnosis.diagnosisreport', verbose_name='首份报告')),
            ],
            options={
                'verbose_name': '病例记录',
                'verbose_name_plural': '病例记录',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ai_report', 'AI诊断报告'), ('doctor_note', '医生记录'), ('follow_up', '随访计划'), ('treatment', '治疗方案')], default='doctor_note', max_length=30, verbose_name='事件类型')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='下次随访时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_events', to=settings.AUTH_USER_MODEL, verbose_name='记录医生')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to='diagnosis.diagnosisreport', verbose_name='关联报告')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diagnosis.caserecord', verbose_name='病例')),
            ],
            options={
                'verbose_name': '病例事件',
                'verbose_name_plural': '病例事件',
                'ordering': ['-created_at'],
            },
        ),
    ]
