# Generated by Django 5.2.1 on 2026-02-11 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_caserecord_caseevent'),
        ('treatment', '0004_treatment_execution_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevent',
            name='related_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to='treatment.treatmentplan', verbose_name='关联治疗方案'),
        ),
    ]
