# Generated by Django 5.2.1 on 2025-12-09 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0002_caserecord_caseevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_grade', models.IntegerField(help_text='0-4级，-1表示适用于所有级别', verbose_name='DR分级')),
                ('lesion_types', models.JSONField(blank=True, default=list, verbose_name='适用病灶类型')),
                ('diabetes_type', models.CharField(blank=True, max_length=20, verbose_name='适用糖尿病类型')),
                ('medications', models.JSONField(default=list, verbose_name='药物列表')),
                ('follow_up_plan', models.JSONField(default=dict, verbose_name='复查计划')),
                ('lifestyle_advice', models.TextField(blank=True, verbose_name='生活方式建议')),
                ('precautions', models.TextField(blank=True, verbose_name='注意事项')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '治疗方案模板',
                'verbose_name_plural': '治疗方案模板',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('patient_unread_count', models.IntegerField(default=0, verbose_name='患者未读数')),
                ('doctor_unread_count', models.IntegerField(default=0, verbose_name='医生未读数')),
                ('last_message', models.TextField(blank=True, verbose_name='最后消息内容')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_conversations', to=settings.AUTH_USER_MODEL, verbose_name='医生')),
                ('last_message_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_conversations', to=settings.AUTH_USER_MODEL, verbose_name='最后消息发送者')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_conversations', to=settings.AUTH_USER_MODEL, verbose_name='患者')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='diagnosis.caserecord', verbose_name='关联病例')),
            ],
            options={
                'verbose_name': '医患会话',
                'verbose_name_plural': '医患会话',
                'ordering': ['-last_message_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='模板标题')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL, verbose_name='医生')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=100, unique=True, verbose_name='方案编号')),
                ('title', models.CharField(max_length=200, verbose_name='方案标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('active', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='方案状态')),
                ('medications', models.JSONField(default=list, verbose_name='药物列表')),
                ('follow_up_plan', models.JSONField(default=dict, verbose_name='复查计划')),
                ('lifestyle_advice', models.TextField(blank=True, verbose_name='生活方式建议')),
                ('precautions', models.TextField(blank=True, verbose_name='注意事项')),
                ('is_ai_recommended', models.BooleanField(default=False, verbose_name='是否AI推荐')),
                ('ai_recommendation_score', models.FloatField(blank=True, null=True, verbose_name='推荐置信度')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始执行日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='预计结束日期')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='diagnosis.caserecord', verbose_name='病例')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='确认医生')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建医生')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='diagnosis.diagnosisreport', verbose_name='关联报告')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='treatment.treatmentplantemplate', verbose_name='使用的模板')),
            ],
            options={
                'verbose_name': '治疗方案',
                'verbose_name_plural': '治疗方案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文字'), ('image', '图片'), ('file', '文件'), ('system', '系统消息')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='文件URL')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='文件名')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='treatment.conversation', verbose_name='会话')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='diagnosis.diagnosisreport', verbose_name='关联报告')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('related_treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='treatment.treatmentplan', verbose_name='关联治疗方案')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(verbose_name='执行日期')),
                ('medication_taken', models.JSONField(default=dict, verbose_name='用药记录')),
                ('follow_up_completed', models.BooleanField(default=False, verbose_name='是否完成复查')),
                ('patient_feedback', models.TextField(blank=True, verbose_name='患者反馈')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='医生备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_executions', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='treatment.treatmentplan', verbose_name='治疗方案')),
            ],
            options={
                'verbose_name': '方案执行记录',
                'verbose_name_plural': '方案执行记录',
                'ordering': ['-execution_date', '-created_at'],
            },
        ),
    ]
