# Generated by Django 5.2.1 on 2026-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='anti_vegf_treatment',
            field=models.JSONField(blank=True, default=dict, verbose_name='抗VEGF治疗方案'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='blood_pressure_target',
            field=models.JSONField(blank=True, default=dict, verbose_name='血压控制目标'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='blood_sugar_target',
            field=models.JSONField(blank=True, default=dict, verbose_name='血糖控制目标'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='diet_guidance',
            field=models.TextField(blank=True, verbose_name='饮食指导'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='exercise_guidance',
            field=models.TextField(blank=True, verbose_name='运动指导'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='laser_treatment',
            field=models.JSONField(blank=True, default=dict, verbose_name='激光治疗方案'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='lipid_management',
            field=models.TextField(blank=True, verbose_name='血脂管理建议'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='monitoring_plan',
            field=models.JSONField(blank=True, default=list, verbose_name='监测计划'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='surgical_treatment',
            field=models.TextField(blank=True, verbose_name='手术治疗指征'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='warning_symptoms',
            field=models.TextField(blank=True, verbose_name='预警症状'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='anti_vegf_treatment',
            field=models.JSONField(blank=True, default=dict, help_text='{"drug": "药物名称", "frequency": "注射频率", "course": "疗程", "notes": "注意事项"}', verbose_name='抗VEGF治疗方案'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='blood_pressure_target',
            field=models.JSONField(blank=True, default=dict, help_text='{"systolic": "收缩压", "diastolic": "舒张压"}', verbose_name='血压控制目标'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='blood_sugar_target',
            field=models.JSONField(blank=True, default=dict, help_text='{"fasting": "空腹血糖", "postprandial": "餐后血糖", "hba1c": "糖化血红蛋白"}', verbose_name='血糖控制目标'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='diet_guidance',
            field=models.TextField(blank=True, verbose_name='饮食指导'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='exercise_guidance',
            field=models.TextField(blank=True, verbose_name='运动指导'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='laser_treatment',
            field=models.JSONField(blank=True, default=dict, help_text='{"type": "类型(PRP/格栅)", "sessions": "次数", "interval": "间隔时间"}', verbose_name='激光治疗方案'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='lipid_management',
            field=models.TextField(blank=True, verbose_name='血脂管理建议'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='monitoring_plan',
            field=models.JSONField(blank=True, default=list, help_text='[{"item": "监测项目", "frequency": "频率", "target": "目标值"}]', verbose_name='监测计划'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='surgical_treatment',
            field=models.TextField(blank=True, help_text='玻切手术适应症描述', verbose_name='手术治疗指征'),
        ),
        migrations.AddField(
            model_name='treatmentplantemplate',
            name='warning_symptoms',
            field=models.TextField(blank=True, help_text='需要立即就医的症状描述', verbose_name='预警症状'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='lifestyle_advice',
            field=models.TextField(blank=True, verbose_name='综合生活方式建议'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='medications',
            field=models.JSONField(default=list, help_text='[{"name": "药物名称", "dosage": "用法用量", "duration": "疗程", "category": "类别", "notes": "备注"}]', verbose_name='药物列表'),
        ),
        migrations.AlterField(
            model_name='treatmentplantemplate',
            name='follow_up_plan',
            field=models.JSONField(default=dict, help_text='{"interval_days": "间隔天数", "check_items": ["检查项目"], "next_date": "下次日期"}', verbose_name='复查计划'),
        ),
        migrations.AlterField(
            model_name='treatmentplantemplate',
            name='lifestyle_advice',
            field=models.TextField(blank=True, verbose_name='综合生活方式建议'),
        ),
        migrations.AlterField(
            model_name='treatmentplantemplate',
            name='medications',
            field=models.JSONField(default=list, help_text='[{"name": "药物名称", "dosage": "用法用量", "duration": "疗程", "category": "类别", "notes": "备注"}]', verbose_name='药物列表'),
        ),
    ]
