# Generated by Django 5.2.1 on 2026-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_treatmentplan_anti_vegf_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='treatments',
            field=models.JSONField(blank=True, default=list, help_text='[{"category": "类别", "item": "具体项目", "frequency": "频率", "course": "疗程", "notes": "备注"}]', verbose_name='治疗项目列表'),
        ),
    ]
