# Generated by Django 5.2.1 on 2026-02-10 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_treatmentplan_treatments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='blood_pressure_diastolic',
            field=models.CharField(blank=True, max_length=20, verbose_name='舒张压(mmHg)'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='blood_pressure_systolic',
            field=models.CharField(blank=True, max_length=20, verbose_name='收缩压(mmHg)'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='blood_sugar_fasting',
            field=models.CharField(blank=True, max_length=20, verbose_name='空腹血糖(mmol/L)'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='blood_sugar_hba1c',
            field=models.CharField(blank=True, max_length=20, verbose_name='糖化血红蛋白(%)'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='blood_sugar_postprandial',
            field=models.CharField(blank=True, max_length=20, verbose_name='餐后血糖(mmol/L)'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='diet_completed',
            field=models.BooleanField(default=False, verbose_name='是否按饮食计划执行'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='diet_notes',
            field=models.TextField(blank=True, verbose_name='饮食记录备注'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='exercise_completed',
            field=models.BooleanField(default=False, verbose_name='是否按运动计划执行'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='exercise_notes',
            field=models.TextField(blank=True, verbose_name='运动记录备注'),
        ),
        migrations.AddField(
            model_name='treatmentplanexecution',
            name='medication_notes',
            field=models.TextField(blank=True, verbose_name='用药备注'),
        ),
        migrations.AlterField(
            model_name='treatmentplanexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_executions', to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
    ]
