# Generated by Django 5.2.1 on 2025-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', '管理員'), ('doctor', '医生'), ('patient', '患者')], default='patient', max_length=10),
        ),
    ]
