# Generated by Django 5.2.1 on 2025-11-23 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_diabetes', models.BooleanField(default=False, verbose_name='是否患有糖尿病')),
                ('diabetes_type', models.CharField(blank=True, choices=[('TYPE1', '1型糖尿病'), ('TYPE2', '2型糖尿病'), ('GESTATIONAL', '妊娠期糖尿病'), ('OTHER', '其他类型'), ('NONE', '无糖尿病')], max_length=20, null=True, verbose_name='糖尿病类型')),
                ('diabetes_duration', models.IntegerField(blank=True, null=True, verbose_name='糖尿病病程（年）')),
                ('blood_sugar_level', models.FloatField(blank=True, null=True, verbose_name='血糖水平（mmol/L）')),
                ('hba1c', models.FloatField(blank=True, null=True, verbose_name='糖化血红蛋白（%）')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='症状列表')),
                ('symptom_description', models.TextField(blank=True, null=True, verbose_name='症状详细描述')),
                ('symptom_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='症状持续时间')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='既往病史')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='家族病史')),
                ('medication_history', models.TextField(blank=True, null=True, verbose_name='用药史')),
                ('allergy_history', models.TextField(blank=True, null=True, verbose_name='过敏史')),
                ('other_conditions', models.TextField(blank=True, null=True, verbose_name='其他疾病')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_info', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '病情信息',
                'verbose_name_plural': '病情信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='详细地址')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='区县')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型'), ('UNKNOWN', '未知')], max_length=10, null=True, verbose_name='血型')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '患者信息',
                'verbose_name_plural': '患者信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
